//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int SaleItemId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
